config/routes.rb
SteamRails::Application.routes.draw do
  root :to => 'achievements#index'
  
  # OmniAuth routes
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#error"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/settings" => "users#edit", :as => :settings
  match "/users/disconnect_twitter" => "users#disconnect_twitter", :as => :disconnect_twitter
  match "/about" => "application#about", :as => :about

  match 'admin' => "admin#index", :as => :admin
  match 'admin/action/:cmd' => "admin#action", :as => :admin_action

  # Catch all for user/game achievement URL
  match '/achievements/search' => 'achievements#search', :as => :search
  match '/a/:user/:game' => 'achievements#show', :as => :achievements
  match '/friends/:user' => 'friends#show', :as => :friends
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= APP_NAME %> <%= " - #{yield :title}" if content_for?(:title) %></title>
    <%= stylesheet_link_tag    "bootstrap-min", "application" %>
    <%= javascript_include_tag "application", params[:controller] %>

    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="apple-touch-icon" href="<%= root_path %>apple-touch-icon.png")
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <span class="brand"><%= link_to APP_NAME, root_path %></span>
          <ul class="nav">
            <% if current_user %>
              <li class="dropdown" data-dropdown="dropdown"><a href="#" class="dropdown-toggle">Achievements</a>
                <ul class="dropdown-menu">
                  <% APP_CONFIG['games'].each do |game| %>
                    <li><%= link_to game['fullname'], achievements_path(:user => current_user.steam_custom_url || current_user.steam_id64, :game => game['shortname']) %></li>
                  <% end %>
                </ul>
              </li>
            <% end %>
            <%= nav_link 'About', about_path %>
          </ul>
          <ul class="nav secondary-nav">
            <% if current_user %>
              <li class="dropdown" data-dropdown="dropdown"><img src="<%= current_user.steam_icon_url %>"><%= link_to current_user.steam_nickname, "#", :class => "dropdown-toggle" %>
                <ul class="dropdown-menu">
                  <li><a target="_new" href="<%= current_user.steam_base_url%>">Steam Profile</a></li>
                  <% if current_user.is_admin %>
                    <li><%= link_to "Site admin", admin_path %></li>
                  <% end %>
                  <li class="divider"></li>
                  <li><%= link_to "Settings", settings_path %></li>
                  <li><%= link_to "Sign Out", signout_path %></li>
                </ul>
              </li>
            <% else %>
              <li><a href="/auth/steam">Connect via Steam</a></li>
              <li><a href="/auth/twitter">...or Twitter</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        <div class="page-header">
          <h1><%= yield :title %></h1>
        </div>
        <div class="row">
          <div class="span10">
            <% flash.each do |name, msg| %>
              <%= content_tag :div, :class => "alert-message #{name}", "data-alert"=> "alert" do -%>
                <a href="#" class="close">x</a>
                <%= raw msg %>
              <% end %>
            <% end %>

            <%= yield %>
          </div>
          <div id="sidebar" class="span4">
              <% if content_for?(:sidebar) %>
                <%= yield :sidebar %>
              <% elsif File.exists?("#{Rails.root}/app/views/#{params[:controller]}/_sidebar.html.erb") %>
    						<%= render "#{params[:controller]}/sidebar", :locals => { :params => params } %>
              <% end %>
          </div>
        </div>
      </div>

      <footer>
        <p>Built by <a href="http://joostschuur.com">Joost Schuur</a><%= " (dev)" if Rails.env.development? %>.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>